name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Get EC2 Instance Public IP
        id: ec2
        run: |
          INSTANCE_ID=i-0910ada535eb85096
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "::set-output name=public_ip::$PUBLIC_IP"
      - name: Check instance
        run: |
          INSTANCE_ID=i-0910ada535eb85096
          set -x 
          aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].State.Name" --output text
      - name: Deploy to EC2 using SSM
        run: |
          set -x 
          INSTANCE_ID=i-0910ada535eb85096
          COMMAND="docker pull ghcr.io/eusorov/docker-project:latest && cd docker-project && docker compose up -d"
          COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceids,Values=$INSTANCE_ID" \
          --parameters 'commands=["'"$COMMAND"'"]' \
          --query "Command.CommandId" \
          --output text)
          aws ssm wait command-executed \
            --instance-id $INSTANCE_ID \
            --command-id $COMMAND_ID
          aws ssm list-command-invocations --command-id $COMMAND_ID --details
