name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Change to your desired region

      - name: Get EC2 Instance Public IP
        id: ec2
        run: |
          INSTANCE_ID=i-0910ada535eb85096
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "::set-output name=public_ip::$PUBLIC_IP"

      - name: Deploy to EC2
        env:
          PUBLIC_IP: ${{ steps.ec2.outputs.public_ip }}
          USER: ${{ secrets.AWS_USER }}  # Your EC2 username (e.g., ec2-user or ubuntu)
        run: |
          echo "Deploying to EC2 instance at $PUBLIC_IP"
          ssh -o StrictHostKeyChecking=no $USER@$PUBLIC_IP << 'EOF'
            docker pull ghcr.io/eusorov/docker-project:latest
            cd docker-project
            docker compose up -d
          EOF
